// Code generated by github.com/kasaikou/goacc, DO NOT EDIT.
// defaultTag=-
package parser

import (
	"encoding/json"

	"golang.org/x/tools/go/packages"
)

type LoadPackageInputBuilder interface {
	Build() *LoadPackageInput
}

// loadPackageInputBuilderImpl is an instance for generating an instance of LoadPackageInput.
type loadPackageInputBuilderImpl struct {
	__lpi *LoadPackageInput
}

// NewLoadPackageInputBuilder creates an LoadPackageInputBuilder instance.
func NewLoadPackageInputBuilder(
	dirname string,
) LoadPackageInputBuilder {
	__lpi := &LoadPackageInput{}

	__lpi.dirname = dirname

	return &loadPackageInputBuilderImpl{__lpi: __lpi}
}

// Build purges LoadPackageInput instance from loadPackageInputBuilderImpl.
//
// If calls other method in loadPackageInputBuilderImpl after Purge called, it will be panic.
func (__lpib *loadPackageInputBuilderImpl) Build() *LoadPackageInput {
	if __lpib == nil {
		panic("loadPackageInputBuilderImpl is nil")
	} else if __lpib.__lpi != nil {
		__lpi := __lpib.__lpi
		__lpib.__lpi = nil

		return __lpi
	}

	panic("LoadPackageInput has been already purged")
}

func (__lpi *LoadPackageInput) MarshalJSON() ([]byte, error) {

	type LoadPackageInputJSONContent struct {
		Dirname string `json:"dirname"`
	}

	return json.Marshal(LoadPackageInputJSONContent{
		Dirname: __lpi.dirname,
	})
}

type ParsePackageInputBuilder interface {
	Build() *ParsePackageInput
}

// parsePackageInputBuilderImpl is an instance for generating an instance of ParsePackageInput.
type parsePackageInputBuilderImpl struct {
	__ppi *ParsePackageInput
}

// NewParsePackageInputBuilder creates an ParsePackageInputBuilder instance.
func NewParsePackageInputBuilder(
	pkg *packages.Package,
	defaultTag string,
) ParsePackageInputBuilder {
	__ppi := &ParsePackageInput{}

	__ppi.pkg = pkg
	__ppi.defaultTag = defaultTag

	return &parsePackageInputBuilderImpl{__ppi: __ppi}
}

// Build purges ParsePackageInput instance from parsePackageInputBuilderImpl.
//
// If calls other method in parsePackageInputBuilderImpl after Purge called, it will be panic.
func (__ppib *parsePackageInputBuilderImpl) Build() *ParsePackageInput {
	if __ppib == nil {
		panic("parsePackageInputBuilderImpl is nil")
	} else if __ppib.__ppi != nil {
		__ppi := __ppib.__ppi
		__ppib.__ppi = nil

		return __ppi
	}

	panic("ParsePackageInput has been already purged")
}

func (__ppi *ParsePackageInput) MarshalJSON() ([]byte, error) {

	type ParsePackageInputJSONContent struct {
		DefaultTag string `json:"defaultTag"`
	}

	return json.Marshal(ParsePackageInputJSONContent{
		DefaultTag: __ppi.defaultTag,
	})
}
