// Code generated by github.com/kasaikou/goacc, DO NOT EDIT.
// defaultTag=-
package entity

type FieldConfigFeaturesBuilder interface {
	Build() *FieldConfigFeatures
}

// fieldConfigFeaturesBuilderImpl is an instance for generating an instance of FieldConfigFeatures.
type fieldConfigFeaturesBuilderImpl struct {
	__fcf *FieldConfigFeatures
}

// NewFieldConfigFeaturesBuilder creates an FieldConfigFeaturesBuilder instance.
func NewFieldConfigFeaturesBuilder(
	usesMutex bool,
	hasRequired bool,
	hasOptional bool,
	hasPtrGetter bool,
	hasGetter bool,
	hasSetter bool,
) FieldConfigFeaturesBuilder {
	__fcf := &FieldConfigFeatures{}

	__fcf.usesMutex = usesMutex
	__fcf.hasRequired = hasRequired
	__fcf.hasOptional = hasOptional
	__fcf.hasPtrGetter = hasPtrGetter
	__fcf.hasGetter = hasGetter
	__fcf.hasSetter = hasSetter

	return &fieldConfigFeaturesBuilderImpl{__fcf: __fcf}
}

// Build purges FieldConfigFeatures instance from fieldConfigFeaturesBuilderImpl.
//
// If calls other method in fieldConfigFeaturesBuilderImpl after Purge called, it will be panic.
func (__fcfb *fieldConfigFeaturesBuilderImpl) Build() *FieldConfigFeatures {
	if __fcfb == nil {
		panic("fieldConfigFeaturesBuilderImpl is nil")
	} else if __fcfb.__fcf != nil {
		__fcf := __fcfb.__fcf
		__fcfb.__fcf = nil

		return __fcf
	}

	panic("FieldConfigFeatures has been already purged")
}

func (__fcf *FieldConfigFeatures) UsesMutex() bool {
	if __fcf != nil {
		return __fcf.usesMutex
	}

	panic("FieldConfigFeatures is nil")
}

func (__fcf *FieldConfigFeatures) HasRequired() bool {
	if __fcf != nil {
		return __fcf.hasRequired
	}

	panic("FieldConfigFeatures is nil")
}

func (__fcf *FieldConfigFeatures) HasOptional() bool {
	if __fcf != nil {
		return __fcf.hasOptional
	}

	panic("FieldConfigFeatures is nil")
}

func (__fcf *FieldConfigFeatures) HasPtrGetter() bool {
	if __fcf != nil {
		return __fcf.hasPtrGetter
	}

	panic("FieldConfigFeatures is nil")
}

func (__fcf *FieldConfigFeatures) HasGetter() bool {
	if __fcf != nil {
		return __fcf.hasGetter
	}

	panic("FieldConfigFeatures is nil")
}

func (__fcf *FieldConfigFeatures) HasSetter() bool {
	if __fcf != nil {
		return __fcf.hasSetter
	}

	panic("FieldConfigFeatures is nil")
}
