// Code generated by github.com/kasaikou/goacc, DO NOT EDIT.
// defaultTag=-
package entity

type ImportConfigBuilder interface {
	Build() *ImportConfig
}

// importConfigBuilderImpl is an instance for generating an instance of ImportConfig.
type importConfigBuilderImpl struct {
	__ic *ImportConfig
}

// NewImportConfigBuilder creates an ImportConfigBuilder instance.
func NewImportConfigBuilder(
	name string,
	path string,
) ImportConfigBuilder {
	__ic := &ImportConfig{}

	__ic.name = name
	__ic.path = path

	return &importConfigBuilderImpl{__ic: __ic}
}

// Build purges ImportConfig instance from importConfigBuilderImpl.
//
// If calls other method in importConfigBuilderImpl after Purge called, it will be panic.
func (__icb *importConfigBuilderImpl) Build() *ImportConfig {
	if __icb == nil {
		panic("importConfigBuilderImpl is nil")
	} else if __icb.__ic != nil {
		__ic := __icb.__ic
		__icb.__ic = nil

		return __ic
	}

	panic("ImportConfig has been already purged")
}
