// Code generated by github.com/kasaikou/goacc, DO NOT EDIT.
// defaultTag=-
package entity

import "encoding/json"

type MetadataBuilder interface {
	SetDefaultTag(defaultTag string) MetadataBuilder
	Build() *Metadata
}

// metadataBuilderImpl is an instance for generating an instance of Metadata.
type metadataBuilderImpl struct {
	__m *Metadata
}

// NewMetadataBuilder creates an MetadataBuilder instance.
func NewMetadataBuilder() MetadataBuilder {
	__m := &Metadata{}

	return &metadataBuilderImpl{__m: __m}
}

func (__mb *metadataBuilderImpl) SetDefaultTag(defaultTag string) MetadataBuilder {
	if __mb == nil {
		panic("metadataBuilderImpl is nil")
	} else if __mb.__m != nil {
		__mb.__m.defaultTag = defaultTag
		return __mb
	}

	panic("Metadata has been already purged")
}

// Build purges Metadata instance from metadataBuilderImpl.
//
// If calls other method in metadataBuilderImpl after Purge called, it will be panic.
func (__mb *metadataBuilderImpl) Build() *Metadata {
	if __mb == nil {
		panic("metadataBuilderImpl is nil")
	} else if __mb.__m != nil {
		__m := __mb.__m
		__mb.__m = nil

		return __m
	}

	panic("Metadata has been already purged")
}

func (__m *Metadata) DefaultTag() string {
	if __m != nil {
		return __m.defaultTag
	}

	panic("Metadata is nil")
}

func (__m *Metadata) MarshalJSON() ([]byte, error) {

	type MetadataJSONContent struct {
		DefaultTag string `json:"defaultTag"`
	}

	return json.Marshal(MetadataJSONContent{
		DefaultTag: __m.defaultTag,
	})
}
