// Code generated by github.com/kasaikou/goacc, DO NOT EDIT.
// defaultTag=-
package entity

import "encoding/json"

// MetadataBuilder is an instance for generating an instance of Metadata.
type MetadataBuilder struct {
	__m *Metadata
}

// NewMetadataBuilder creates an MetadataBuilder instance.
func NewMetadataBuilder() *MetadataBuilder {
	__m := &Metadata{}

	return &MetadataBuilder{__m: __m}
}

func (__mb *MetadataBuilder) SetDefaultTag(defaultTag string) *MetadataBuilder {
	if __mb == nil {
		panic("MetadataBuilder is nil")
	} else if __mb.__m != nil {
		__mb.__m.defaultTag = defaultTag
		return __mb
	}

	panic("Metadata has been already purged")
}

// Purge purges Metadata instance from MetadataBuilder.
//
// If calls other method in MetadataBuilder after Purge called, it will be panic.
func (__mb *MetadataBuilder) Build() *Metadata {
	if __mb == nil {
		panic("MetadataBuilder is nil")
	} else if __mb.__m != nil {
		__m := __mb.__m
		__mb.__m = nil

		return __m
	}

	panic("Metadata has been already purged")
}

func (__m *Metadata) DefaultTag() string {
	if __m != nil {
		return __m.defaultTag
	}

	panic("Metadata is nil")
}

func (__m *Metadata) MarshalJSON() ([]byte, error) {

	type MetadataJSONContent struct {
		DefaultTag string `json:"defaultTag"`
	}

	return json.Marshal(MetadataJSONContent{
		DefaultTag: __m.defaultTag,
	})
}
