// Code generated by github.com/kasaikou/goacc, DO NOT EDIT.
// defaultTag=-
package entity

type StructSupportsBuilder interface {
	SetHasPreNewHook(hasPreNewHook bool) StructSupportsBuilder
	SetHasPostNewHook(hasPostNewHook bool) StructSupportsBuilder
	SetHasPostNewHookError(hasPostNewHookError bool) StructSupportsBuilder
	Build() *StructSupports
}

// structSupportsBuilderImpl is an instance for generating an instance of StructSupports.
type structSupportsBuilderImpl struct {
	__ss *StructSupports
}

// NewStructSupportsBuilder creates an StructSupportsBuilder instance.
func NewStructSupportsBuilder() StructSupportsBuilder {
	__ss := &StructSupports{}

	return &structSupportsBuilderImpl{__ss: __ss}
}

func (__ssb *structSupportsBuilderImpl) SetHasPreNewHook(hasPreNewHook bool) StructSupportsBuilder {
	if __ssb == nil {
		panic("structSupportsBuilderImpl is nil")
	} else if __ssb.__ss != nil {
		__ssb.__ss.hasPreNewHook = hasPreNewHook
		return __ssb
	}

	panic("StructSupports has been already purged")
}

func (__ssb *structSupportsBuilderImpl) SetHasPostNewHook(hasPostNewHook bool) StructSupportsBuilder {
	if __ssb == nil {
		panic("structSupportsBuilderImpl is nil")
	} else if __ssb.__ss != nil {
		__ssb.__ss.hasPostNewHook = hasPostNewHook
		return __ssb
	}

	panic("StructSupports has been already purged")
}

func (__ssb *structSupportsBuilderImpl) SetHasPostNewHookError(hasPostNewHookError bool) StructSupportsBuilder {
	if __ssb == nil {
		panic("structSupportsBuilderImpl is nil")
	} else if __ssb.__ss != nil {
		__ssb.__ss.hasPostNewHookError = hasPostNewHookError
		return __ssb
	}

	panic("StructSupports has been already purged")
}

// Build purges StructSupports instance from structSupportsBuilderImpl.
//
// If calls other method in structSupportsBuilderImpl after Purge called, it will be panic.
func (__ssb *structSupportsBuilderImpl) Build() *StructSupports {
	if __ssb == nil {
		panic("structSupportsBuilderImpl is nil")
	} else if __ssb.__ss != nil {
		__ss := __ssb.__ss
		__ssb.__ss = nil

		return __ss
	}

	panic("StructSupports has been already purged")
}

func (__ss *StructSupports) HasPreNewHook() bool {
	if __ss != nil {
		return __ss.hasPreNewHook
	}

	panic("StructSupports is nil")
}

func (__ss *StructSupports) HasPostNewHook() bool {
	if __ss != nil {
		return __ss.hasPostNewHook
	}

	panic("StructSupports is nil")
}

func (__ss *StructSupports) HasPostNewHookError() bool {
	if __ss != nil {
		return __ss.hasPostNewHookError
	}

	panic("StructSupports is nil")
}
