// Code generated by github.com/kasaikou/goacc, DO NOT EDIT.
// defaultTag=-
package tests

type ValidatedBuilder interface {
	Build() (*Validated, error)
}

// validatedBuilderImpl is an instance for generating an instance of Validated.
type validatedBuilderImpl struct {
	__v *Validated
}

// NewValidatedBuilder creates an ValidatedBuilder instance.
func NewValidatedBuilder(
	Type string,
) ValidatedBuilder {
	__v := &Validated{}

	__v.Type = Type

	return &validatedBuilderImpl{__v: __v}
}

// Build purges Validated instance from validatedBuilderImpl.
//
// If calls other method in validatedBuilderImpl after Purge called, it will be panic.
func (__vb *validatedBuilderImpl) Build() (*Validated, error) {
	if __vb == nil {
		panic("validatedBuilderImpl is nil")
	} else if __vb.__v != nil {
		__v := __vb.__v
		__vb.__v = nil

		err := __v.goaccPostNewHook() // This function calls your defined hook.
		return __v, err
	}

	panic("Validated has been already purged")
}
