// Code generated by github.com/kasaikou/goacc, DO NOT EDIT.
// defaultTag=-
package tests

// ValidatedBuilder is an instance for generating an instance of Validated.
type ValidatedBuilder struct {
	__v *Validated
}

// NewValidatedBuilder creates an ValidatedBuilder instance.
func NewValidatedBuilder(
	Type string,
) *ValidatedBuilder {
	__v := &Validated{}

	__v.Type = Type

	return &ValidatedBuilder{__v: __v}
}

// Purge purges Validated instance from ValidatedBuilder.
//
// If calls other method in ValidatedBuilder after Purge called, it will be panic.
func (__vb *ValidatedBuilder) Build() (*Validated, error) {
	if __vb == nil {
		panic("ValidatedBuilder is nil")
	} else if __vb.__v != nil {
		__v := __vb.__v
		__vb.__v = nil

		err := __v.goaccPostNewHook() // This function calls your defined hook.
		return __v, err
	}

	panic("Validated has been already purged")
}
