// Code generated by github.com/kasaikou/goacc, DO NOT EDIT.
package generator

import (
	"encoding/json"

	"github.com/kasaikou/goacc/goacc/entity"
)

func (__g *Generator) MarshalJSON() ([]byte, error) {

	type GeneratorJSONContent struct {
		Cache map[string]*entity.FileConfig `json:"cache"`
	}

	return json.Marshal(GeneratorJSONContent{
		Cache: __g.cache,
	})
}
